import type { Report } from "../demo-data";

export const demoReports: Report[] = [
  {
    id: "1",
    title: "Asset Inventory Overview",
    description: "An overview of all assets currently in inventory.",
    type: "asset",
    columns: ["name", "tag", "type", "manufacturer"],
    status: "active",
    createdAt: "2024-12-01T12:00:00Z",
    updatedAt: "2024-12-01T12:00:00Z",
    user: {
      id: "user1",
      name: "John Doe",
      username: "jdoe",
    },
  },
  {
    id: "2",
    title: "Asset Utilization Trends",
    description: "Insights into how assets are being utilized over time.",
    type: "asset",
    columns: ["name", "tag", "type", "manufacturer"],
    status: "active",
    createdAt: "2024-12-01T12:00:00Z",
    updatedAt: "2024-12-01T12:00:00Z",
    user: {
      id: "user1",
      name: "John Doe",
      username: "jdoe",
    },
  },
  {
    id: "3",
    title: "Underperforming Assets Report",
    description:
      "Identify assets that are not meeting performance expectations.",
    type: "asset",
    columns: ["name", "tag", "type", "manufacturer"],
    status: "active",
    createdAt: "2024-12-01T12:00:00Z",
    updatedAt: "2024-12-01T12:00:00Z",
    user: {
      id: "user1",
      name: "John Doe",
      username: "jdoe",
    },
  },
  {
    id: "4",
    title: "Asset Depreciation Analysis",
    description: "A detailed analysis of asset depreciation values.",
    type: "asset",
    columns: ["name", "tag", "type", "manufacturer"],
    status: "active",
    createdAt: "2024-12-01T12:00:00Z",
    updatedAt: "2024-12-01T12:00:00Z",
    user: {
      id: "user1",
      name: "John Doe",
      username: "jdoe",
    },
  },
  {
    id: "5",
    title: "Asset Repair History",
    description: "A history of repairs performed on all assets.",
    type: "asset",
    columns: ["name", "tag", "type", "manufacturer"],
    status: "active",
    createdAt: "2024-12-01T12:00:00Z",
    updatedAt: "2024-12-01T12:00:00Z",
    user: {
      id: "user1",
      name: "John Doe",
      username: "jdoe",
    },
  },
  {
    id: "6",
    title: "Assets Near End of Life",
    description:
      "Identify assets that are nearing the end of their usable life.",
    type: "asset",
    columns: ["name", "tag", "type", "manufacturer"],
    status: "active",
    createdAt: "2024-12-01T12:00:00Z",
    updatedAt: "2024-12-01T12:00:00Z",
    user: {
      id: "user1",
      name: "John Doe",
      username: "jdoe",
    },
  },
  {
    id: "7",
    title: "Newly Acquired Assets",
    description: "Track recently acquired assets.",
    type: "asset",
    columns: ["name", "tag", "type", "manufacturer"],
    status: "active",
    createdAt: "2024-12-01T12:00:00Z",
    updatedAt: "2024-12-01T12:00:00Z",
    user: {
      id: "user1",
      name: "John Doe",
      username: "jdoe",
    },
  },
  {
    id: "8",
    title: "Idle Assets by Location",
    description:
      "Report on assets that are not actively being used, grouped by location.",
    type: "asset",
    columns: ["name", "tag", "type", "manufacturer"],
    status: "active",
    createdAt: "2024-12-01T12:00:00Z",
    updatedAt: "2024-12-01T12:00:00Z",
    user: {
      id: "user1",
      name: "John Doe",
      username: "jdoe",
    },
  },
  {
    id: "9",
    title: "Asset Maintenance Schedule Compliance",
    description:
      "Check if maintenance schedules are being adhered to for assets.",
    type: "asset",
    columns: ["name", "tag", "type", "manufacturer"],
    status: "active",
    createdAt: "2024-12-01T12:00:00Z",
    updatedAt: "2024-12-01T12:00:00Z",
    user: {
      id: "user1",
      name: "John Doe",
      username: "jdoe",
    },
  },
  {
    id: "10",
    title: "Top 10 Most Valuable Assets",
    description: "List of the most valuable assets currently in inventory.",
    type: "asset",
    columns: ["name", "tag", "type", "manufacturer"],
    status: "active",
    createdAt: "2024-12-01T12:00:00Z",
    updatedAt: "2024-12-01T12:00:00Z",
    user: {
      id: "user1",
      name: "John Doe",
      username: "jdoe",
    },
  },
];
